language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 342015504a9d7322f6ed497e9dbdf57603e85a4e
  keep-history: true
  on:
    branch: master
