language: node_js
node_js:
- lts/*
script:
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
