name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master
permissions:
  contents: write      

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Install and Build 
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm ci
          npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          AlEI_TOKEN: ${{ secrets.AlEI_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

